import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "@/Components/Home/Header/Header";
import Searchfield from "@/Components/Home/Searchfield/Searchfield";
import SellAndRent from "@/Components/Home/SellAndRent/SellAndRent";
import About from "@/Components/Home/About/About";
import Welcome from "@/Components/Home/Welcome/Welcome";
import Hero from "@/Components/Home/Hero/Hero";
import Branding from "@/Components/Home/Branding/Branding";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>LeasHome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero></Hero>
        <Searchfield></Searchfield>
        <SellAndRent></SellAndRent>
        <Branding />
        <Header></Header>
        <Welcome></Welcome>
        <About></About>
      </main>
    </>
  );
}
